graph TB
    subgraph "메인 계층"
        App["App<br/>메인 앱"]
        Index["index.js<br/>진입점"]
    end
    
    subgraph "컨트롤러 계층"
        GC["GameController<br/>게임 흐름 제어"]
    end
    
    subgraph "도메인 계층"
        Car["Car<br/>자동차 모델"]
    end
    
    subgraph "뷰 계층"
        GV["GameView<br/>UI 출력"]
    end
    
    subgraph "유틸리티 계층"
        Validator["Validator<br/>검증 로직"]
        Constants["constants.js<br/>상수 정의"]
        ErrorMsg["ErrorMessage<br/>에러 메시지"]
    end
    
    Index --> App
    App --> GC
    GC --> GV
    GC --> Validator
    GC --> Car
    GV --> Validator
    Validator --> Constants
    Validator --> ErrorMsg
    Car --> Constants

